version: "3.6"
services:
  web:
    container_name: nexus_assess_backend_web
    tty: true
    stdin_open: true
    build:
      context: .
    restart: always
    volumes:
      - .:/web
    ports:
      - "8000:8000"
    env_file:
      - .env

  redis:
    container_name: nexus_assess_backend_redis
    image: redis:alpine
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  celery:
    container_name: nexus_assess_backend_celery
    depends_on:
      - web
      - redis
    build:
      context: .
    restart: always
    volumes:
      - .:/web
    env_file:
      - .env
    command: bash -c "celery -A nexus_assess_backend worker --beat --loglevel=info"
    # command: bash -c "celery -A nexus_assess_backend worker --loglevel=info --concurrency=1 --prefetch-multiplier=1 --time-limit=300"
