# Generated by Django 4.2.7 on 2023-12-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0002_alter_compliancecrititcalityassessment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancecrititcalityassessment",
            name="server_host",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Server Host / Loaction",
            ),
        ),
        migrations.AddField(
            model_name="compliancecrititcalityassessment",
            name="solution_version",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Solution version"
            ),
        ),
        migrations.AddField(
            model_name="compliancecrititcalityassessment",
            name="vendor_name",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Vendor Name"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="output_csv_1",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Output CSV 1"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="output_docx_1",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Output Docx 1"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="output_xlsm_1",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Output XLSM 1"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="output_xlsm_2",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Output XLSM 2"
            ),
        ),
    ]
