# Generated by Django 4.2.8 on 2023-12-19 09:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assessments", "0003_compliancecrititcalityassessment_server_host_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ComplianceCrititcalityAssessment",
            new_name="ComplianceCriticalityAssessment",
        ),
    ]
