# Generated by Django 4.2.8 on 2024-01-02 06:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "assessments",
            "0004_rename_compliancecrititcalityassessment_compliancecriticalityassessment",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="compliancecriticalityassessment",
            options={
                "verbose_name": "Compliance Criticality Assessment",
                "verbose_name_plural": "Compliance Criticality Assessments",
            },
        ),
    ]
