# Generated by Django 4.2.9 on 2024-01-11 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_managers_remove_user_username_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assessments", "0005_alter_compliancecriticalityassessment_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compliancecriticalityassessment",
            name="user",
        ),
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="approved_by_business_owner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="approved_by_it_risk_management_and_compliance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="approved_by_system_owner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="business_owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cca_business_owner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Business Owner",
            ),
        ),
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="drafted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cca_drafts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="it_risk_management_and_compliance",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cca_it_risk_management_and_compliance",
                to=settings.AUTH_USER_MODEL,
                verbose_name="IT Risk Management and Compliance",
            ),
        ),
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="other_solution_type",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="If other, please specify",
            ),
        ),
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="solution_classification",
            field=models.CharField(
                choices=[
                    ("custom", "Custom"),
                    ("configurable", "Configurable"),
                    ("non_configurable", "Non-configurable (out-of-the-box)"),
                ],
                max_length=50,
                null=True,
                verbose_name="Solution Clasification",
            ),
        ),
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="solution_type",
            field=models.CharField(
                choices=[
                    ("application", "Application"),
                    ("infrastucture", "Infrastructure Platform"),
                    ("middleware", "Middleware"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
                verbose_name="Type of Solution",
            ),
        ),
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("for_review", "For Review"),
                    ("for_revision", "For Revision"),
                    ("approved", "Approved"),
                ],
                default="draft",
                max_length=50,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="system_owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cca_system_owner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="System Owner",
            ),
        ),
        migrations.AlterField(
            model_name="compliancecriticalityassessment",
            name="server_host",
            field=models.CharField(
                max_length=256, null=True, verbose_name="Server Host / Loaction"
            ),
        ),
        migrations.AlterField(
            model_name="compliancecriticalityassessment",
            name="vendor_name",
            field=models.CharField(
                max_length=256, null=True, verbose_name="Vendor Name"
            ),
        ),
    ]
