# Generated by Django 4.2.9 on 2024-01-12 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assessments", "0006_remove_compliancecriticalityassessment_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliancecriticalityassessment",
            name="drafted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cca_drafts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Drafted By",
            ),
        ),
        migrations.CreateModel(
            name="ReviewComments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("comment", models.CharField(max_length=256, verbose_name="Comment")),
                (
                    "cca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="assessments.compliancecriticalityassessment",
                        verbose_name="Compliance Criticality Assessment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cca_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Comment",
                "verbose_name_plural": "Review Comments",
            },
        ),
    ]
