# Generated by Django 4.2.9 on 2024-01-12 05:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "assessments",
            "0007_alter_compliancecriticalityassessment_drafted_by_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ReviewComments",
            new_name="ReviewComment",
        ),
    ]
