# Generated by Django 4.2.9 on 2024-01-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0008_rename_reviewcomments_reviewcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="datetime_approved_by_business_owner",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="datetime_approved_by_it_risk_management_and_compliance",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="datetime_approved_by_system_owner",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
