# Generated by Django 4.2.9 on 2024-01-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "assessments",
            "0009_compliancecriticalityassessment_datetime_approved_by_business_owner_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="hosting_and_type",
            field=models.CharField(
                choices=[
                    ("third_party", "Third Party Hosting"),
                    ("on_premises", "On-Premises"),
                    ("website", "Website (Public)"),
                    ("saas", "Software As a Service (Saas)"),
                    ("paas", "Platform As a Service (Paas)"),
                    ("iaas", "Infrastructure As a Service (IAAS)"),
                ],
                max_length=50,
                null=True,
                verbose_name="Hosting and Type",
            ),
        ),
        migrations.AlterField(
            model_name="compliancecriticalityassessment",
            name="server_host",
            field=models.CharField(
                max_length=256, null=True, verbose_name="Server Host / Location"
            ),
        ),
    ]
