# Generated by Django 4.2.9 on 2024-01-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "assessments",
            "0010_compliancecriticalityassessment_hosting_and_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliancecriticalityassessment",
            name="solution_type",
            field=models.CharField(
                choices=[
                    ("application", "Application"),
                    ("infrastucture", "Infrastructure Platform"),
                    ("middleware", "Middleware"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
                verbose_name="Solution Type",
            ),
        ),
        migrations.AlterField(
            model_name="compliancecriticalityassessment",
            name="solution_version",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Software Release / Version, as applicable",
            ),
        ),
    ]
