# Generated by Django 4.2.9 on 2024-01-22 02:52

import assessments.applogic
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "assessments",
            "0012_alter_compliancecriticalityassessment_solution_type",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="summary",
            field=models.JSONField(
                default=assessments.applogic.get_default_summary_json_value,
                validators=[assessments.applogic.validate_summary_json],
                verbose_name="Summary",
            ),
        ),
    ]
