# Generated by Django 4.2.9 on 2024-01-24 04:08

import assessments.applogic
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0013_compliancecriticalityassessment_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="gxp_impact",
            field=models.JSONField(
                default=assessments.applogic.get_default_summary_json_value,
                verbose_name="GxP Impact",
            ),
        ),
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="solution_description",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Solution Description and Intended Use",
            ),
        ),
    ]
