# Generated by Django 4.2.9 on 2024-01-24 12:05

import assessments.applogic.business_impact_applogic
import assessments.applogic.data_classification_applogic
import assessments.applogic.gxp_eres_applogic
import assessments.applogic.gxp_impact_applogic
import assessments.applogic.privacy_impact_applogic
import assessments.applogic.rating_applogic
import assessments.applogic.sox_impact_applogic
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0014_compliancecriticalityassessment_gxp_impact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="business_impact",
            field=models.JSONField(
                default=assessments.applogic.business_impact_applogic.get_default_business_impact_json_value,
                validators=[
                    assessments.applogic.business_impact_applogic.validate_business_impact_json
                ],
                verbose_name="Business Impact",
            ),
        ),
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="data_classification",
            field=models.JSONField(
                default=assessments.applogic.data_classification_applogic.get_default_data_classification_json_value,
                validators=[
                    assessments.applogic.data_classification_applogic.validate_data_classification_json
                ],
                verbose_name="Data Classification",
            ),
        ),
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="gxp_eres",
            field=models.JSONField(
                default=assessments.applogic.gxp_eres_applogic.get_default_gxp_eres_json_value,
                validators=[
                    assessments.applogic.gxp_eres_applogic.validate_gxp_eres_json
                ],
                verbose_name="GxP Electronic Records (ER) and Electronic Signatures (ES) Applicability",
            ),
        ),
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="privacy_impact",
            field=models.JSONField(
                default=assessments.applogic.privacy_impact_applogic.get_default_privacy_impact_json_value,
                validators=[
                    assessments.applogic.privacy_impact_applogic.validate_privacy_impact_json
                ],
                verbose_name="Privacy Impact",
            ),
        ),
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="rating",
            field=models.JSONField(
                default=assessments.applogic.rating_applogic.get_default_rating_json_value,
                validators=[assessments.applogic.rating_applogic.validate_rating_json],
                verbose_name="Compliance Criticality Rating",
            ),
        ),
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="sox_impact",
            field=models.JSONField(
                default=assessments.applogic.sox_impact_applogic.get_default_sox_impact_json_value,
                validators=[
                    assessments.applogic.sox_impact_applogic.validate_sox_impact_json
                ],
                verbose_name="SOX Impact",
            ),
        ),
        migrations.AlterField(
            model_name="compliancecriticalityassessment",
            name="gxp_impact",
            field=models.JSONField(
                default=assessments.applogic.gxp_impact_applogic.get_default_gxp_impact_json_value,
                validators=[
                    assessments.applogic.gxp_impact_applogic.validate_gxp_impact_json
                ],
                verbose_name="GxP Impact",
            ),
        ),
    ]
