# Generated by Django 4.2.9 on 2024-01-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "assessments",
            "0015_compliancecriticalityassessment_business_impact_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliancecriticalityassessment",
            name="approved_by_business_owner",
            field=models.BooleanField(
                default=False, verbose_name="Approved by Business Owner"
            ),
        ),
        migrations.AlterField(
            model_name="compliancecriticalityassessment",
            name="approved_by_it_risk_management_and_compliance",
            field=models.BooleanField(
                default=False,
                verbose_name="Approved by IT Risk Management and Compliance",
            ),
        ),
        migrations.AlterField(
            model_name="compliancecriticalityassessment",
            name="approved_by_system_owner",
            field=models.BooleanField(
                default=False, verbose_name="Approved by System Owner"
            ),
        ),
        migrations.AlterField(
            model_name="compliancecriticalityassessment",
            name="datetime_approved_by_business_owner",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approved on"
            ),
        ),
        migrations.AlterField(
            model_name="compliancecriticalityassessment",
            name="datetime_approved_by_it_risk_management_and_compliance",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approved on"
            ),
        ),
        migrations.AlterField(
            model_name="compliancecriticalityassessment",
            name="datetime_approved_by_system_owner",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approved on"
            ),
        ),
    ]
