# Generated by Django 4.2.9 on 2024-02-02 09:42

from django.db import migrations, models


def generate_form_name(apps, schema_editor):
    ComplianceCriticalityAssessment = apps.get_model(
        "assessments", "ComplianceCriticalityAssessment"
    )

    for cca in ComplianceCriticalityAssessment.objects.all():
        cca.name = f"Form #{cca.id}"
        cca.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessments",
            "0016_alter_compliancecriticalityassessment_approved_by_business_owner_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancecriticalityassessment",
            name="name",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Form Name"
            ),
        ),
        migrations.RunPython(generate_form_name, migrations.RunPython.noop),
    ]
