# Generated by Django 4.2.9 on 2024-02-15 06:38

import assessments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0017_compliancecriticalityassessment_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="output_csv_1",
        ),
        migrations.AlterField(
            model_name="report",
            name="output_docx_1",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=assessments.models.upload_report_to,
                verbose_name="Output Docx 1",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="output_xlsm_1",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=assessments.models.upload_report_to,
                verbose_name="Output XLSM 1",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="output_xlsm_2",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=assessments.models.upload_report_to,
                verbose_name="Output XLSM 2",
            ),
        ),
    ]
