# Generated by Django 4.2.10 on 2024-02-16 05:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0018_remove_report_output_csv_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="report",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="report",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="report",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="cca",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="assessments.compliancecriticalityassessment",
                verbose_name="Criticality Assessment",
            ),
        ),
    ]
