# Generated by Django 4.2.10 on 2024-02-16 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "assessments",
            "0019_remove_report_created_at_remove_report_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        blank=True,
                        max_length=256,
                        null=True,
                        upload_to="exports/",
                        verbose_name="Document File",
                    ),
                ),
                (
                    "exported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Exported By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment Export",
                "verbose_name_plural": "Assessment Exports",
            },
        ),
    ]
