# Generated by Django 4.2.10 on 2024-02-19 03:15

import assessments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessments",
            "0020_assessmentexport",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="output_docx_1",
        ),
        migrations.AddField(
            model_name="report",
            name="compressed_reports",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=assessments.models.upload_report_to,
                verbose_name="Compressed Reports",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="output_cca_doc",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=assessments.models.upload_report_to,
                verbose_name="CCA Document",
            ),
        ),
    ]
