# Generated by Django 4.2.10 on 2024-02-19 09:08

from django.db import migrations


def create_report_for_existing_cca(apps, schema_editor):
    Report = apps.get_model("assessments", "Report")
    ComplianceCriticalityAssessment = apps.get_model(
        "assessments", "ComplianceCriticalityAssessment"
    )

    for cca in ComplianceCriticalityAssessment.objects.all():
        # Check if a Report already exists for the current CCA
        if not Report.objects.filter(cca=cca).exists():
            Report.objects.create(cca=cca)


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0021_remove_report_output_docx_1_and_more"),
    ]

    operations = [
        migrations.RunPython(create_report_for_existing_cca, migrations.RunPython.noop),
    ]
