# Generated by Django 4.2.10 on 2024-02-20 02:31

import assessments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0022_auto_20240219_0908"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="compressed_reports",
            field=models.FileField(
                blank=True,
                help_text="This is a zipped file containing all the Report files above.",
                null=True,
                upload_to=assessments.models.upload_report_to,
                verbose_name="All Reports",
            ),
        ),
    ]
