# Generated by Django 4.2.10 on 2024-03-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0023_alter_report_compressed_reports"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliancecriticalityassessment",
            name="approved_by_business_owner",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Approved by Business Owner",
            ),
        ),
        migrations.AlterField(
            model_name="compliancecriticalityassessment",
            name="approved_by_it_risk_management_and_compliance",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Approved by IT Risk Management and Compliance",
            ),
        ),
        migrations.AlterField(
            model_name="compliancecriticalityassessment",
            name="approved_by_system_owner",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Approved by System Owner",
            ),
        ),
    ]
