# Generated by Django 4.2.7 on 2023-12-06 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Compliance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Compliance",
                "verbose_name_plural": "Compliance",
            },
        ),
        migrations.CreateModel(
            name="ComplianceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
            ],
            options={
                "verbose_name": "ComplianceCategory",
                "verbose_name_plural": "ComplianceCategories",
            },
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(max_length=256, verbose_name="Identifier"),
                ),
            ],
            options={
                "verbose_name": "Reference",
                "verbose_name_plural": "References",
            },
        ),
        migrations.CreateModel(
            name="ReferenceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
            ],
            options={
                "verbose_name": "ReferenceCategory",
                "verbose_name_plural": "ReferenceCategories",
            },
        ),
        migrations.CreateModel(
            name="RequirementCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
            ],
            options={
                "verbose_name": "RequirementCategory",
                "verbose_name_plural": "RequirementCategories",
            },
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "control_id",
                    models.CharField(max_length=50, verbose_name="Control ID"),
                ),
                (
                    "control_statement",
                    models.TextField(verbose_name="Control Statement"),
                ),
                (
                    "requirement_statement",
                    models.TextField(verbose_name="Requirement Statement"),
                ),
                ("test_guide", models.TextField(verbose_name="Test Guide")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requirements.requirementcategory",
                        verbose_name="Category",
                    ),
                ),
                (
                    "compliances",
                    models.ManyToManyField(
                        to="requirements.compliance", verbose_name="Compliances"
                    ),
                ),
                (
                    "references",
                    models.ManyToManyField(
                        to="requirements.reference", verbose_name="References"
                    ),
                ),
            ],
            options={
                "verbose_name": "Requirement",
                "verbose_name_plural": "Requirements",
            },
        ),
        migrations.CreateModel(
            name="ReferencePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requirements.referencecategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "ReferencePolicy",
                "verbose_name_plural": "ReferencePolicies",
            },
        ),
        migrations.AddField(
            model_name="reference",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="requirements.referencepolicy",
                verbose_name="Reference Policy",
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="requirements.compliancecategory",
            ),
        ),
    ]
