# Generated by Django 4.2.9 on 2024-01-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requirements", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requirement",
            name="test_guide",
        ),
        migrations.AddField(
            model_name="compliance",
            name="header_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="referencepolicy",
            name="header_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Header Name"
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="analytical_instruments",
            field=models.BooleanField(
                default=False, verbose_name="Analytical Instruments"
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="baseline",
            field=models.BooleanField(default=False, verbose_name="Baseline"),
        ),
        migrations.AddField(
            model_name="requirement",
            name="bbb_common_solution",
            field=models.TextField(
                blank=True, null=True, verbose_name="bbb Common Solution"
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="iaas_infrastructure",
            field=models.BooleanField(
                default=False, verbose_name="IaaS/Infrastructure"
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="organization",
            field=models.BooleanField(default=False, verbose_name="Organization"),
        ),
        migrations.AddField(
            model_name="requirement",
            name="paas",
            field=models.BooleanField(default=False, verbose_name="PaaS"),
        ),
        migrations.AddField(
            model_name="requirement",
            name="saas_application",
            field=models.BooleanField(default=False, verbose_name="SaaS/Application"),
        ),
        migrations.AddField(
            model_name="requirement",
            name="test_guidance",
            field=models.TextField(blank=True, null=True, verbose_name="Test Guidance"),
        ),
    ]
