# Generated by Django 4.2.9 on 2024-01-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "requirements",
            "0002_remove_requirement_test_guide_compliance_header_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliance",
            name="header_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Header Name"
            ),
        ),
    ]
