# Generated by Django 4.2.9 on 2024-02-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requirements", "0004_alter_compliancecategory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliance",
            name="reference_policies",
            field=models.ManyToManyField(
                to="requirements.referencepolicy",
                verbose_name="Related Refence Policies",
            ),
        ),
    ]
