# Generated by Django 4.2.9 on 2024-02-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requirements", "0005_compliance_reference_policies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliance",
            name="reference_policies",
            field=models.ManyToManyField(
                blank=True,
                to="requirements.referencepolicy",
                verbose_name="Related Refence Policies",
            ),
        ),
    ]
